const GET_REPOS_SUCCESS = 'repos/GET_REPOS_SUCCESS';
const UPDATE_QUERY_REQUEST = 'repos/UPDATE_QUERY_REQUEST';
const FETCH_REQUEST = 'repos/FETCH_REQUEST';
const FETCH_ERROR = 'repos/FETCH_ERROR';

export default {
  GET_REPOS_SUCCESS,
  UPDATE_QUERY_REQUEST,
  FETCH_REQUEST,
  FETCH_ERROR,
};
